### PR TITLE
Add three more pkgs

### PR DESCRIPTION
**Pull request by GeorgianaElena**
For https://2i2c.freshdesk.com/a/tickets/1407

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]
Just an FYI, according to the runbook, you can self-merge these without review if the build succeeds https://infrastructure.2i2c.org/sre-guide/support/simple-python-package/#does-the-build-succeed

**Comment by consideRatio** [comment]
WAIT

**Review by consideRatio — CHANGES_REQUESTED** [review]
Wait, I'd like this to be discussed a bit - updating this comment soon.

EDIT: for now 2i2c internal discussion initiated at https://2i2c.slack.com/archives/C028WU9PFBN/p1710324397830509

**Comment by consideRatio** [comment]
I figure by merging this, we transition this from being a general purpose image with nbgitpuller added to it to become a ucmerced specific image for ucmerced specifically.

This is acceptable to do, but I think we should make sure everyone seeing this repo and image name gets its a ucmerced specific image.

---

I've dismissed by "request for changes" for now, I don't want to block this for ucmerced.

**Comment by GeorgianaElena** [comment]
@consideRatio, agree! I believe we should keep this image and repo as it is as we might need it for other hubs until the nbgitpuller is shipped with the uptream image?

I believe the options we have atm to push this forward is to either:
- create a new repo for the ucmerced image based of this image to which we add the pkgs in this PR
- or have the community create this new repo under their organization so they feel empowered to build on top it in the future

The second option seems the way to go and I believe @jmunroe already shared the new amazing docs on how to achieve this https://docs.2i2c.org/how-to-guides/add-packages-to-image/. So I think this PR can be closed maybe.

**Comment by jmunroe** [comment]
I met with UC Merced yesterday afternoon. The plan is for them to  use the provided documentation on creating and maintaining their own image repo.

I agree that this particular PR is not required but the repo itself should be kept.

**Comment by GeorgianaElena** [comment]
Great news @jmunroe! Thanks for the input, closing this PR now.

**Pull request closed without merging**
